name: widgetbook_workspace
description: "Form&Fun Flutter Test - Widgetbook Workspace"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  lottie: ^3.3.2
  formfun_flutter_test:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.20.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ff_logo.png
    - assets/images/ff_website.png
    - assets/images/icon_html.svg
    - assets/lottie/searching.json

  fonts:
    - family: Aktiv Grotesk
      fonts:
        - asset: assets/font/AktivGrotesk_Blk.ttf
          weight: 900
        - asset: assets/font/AktivGrotesk_XBd.ttf
          weight: 800
        - asset: assets/font/AktivGrotesk_Bd.ttf
          weight: 700
        - asset: assets/font/AktivGrotesk_SBd.ttf
          weight: 600
        - asset: assets/font/AktivGrotesk_Md.ttf
          weight: 500
        - asset: assets/font/AktivGrotesk_Rg.ttf
          weight: 400
        - asset: assets/font/AktivGrotesk_Lt.ttf
          weight: 300
        - asset: assets/font/AktivGrotesk_Th.ttf
          weight: 200
        - asset: assets/font/AktivGrotesk_Hair.ttf
          weight: 100